trigger: 
- master

pool: 
  name: Default

variables:
- group: 'SharedVariables'

stages:
  - stage: Building
    jobs:
    - job: Build
      steps:
        # TODO Files don't get their version's date. So always builds.
      - checkout: self
        clean: false
        submodules: recursive
      - task: NuGetToolInstaller@1
      - task: NuGetCommand@2
        inputs:
          restoreSolution: $(solution)
      - task: VSBuild@1
        displayName: 'Build solution'
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:WarningLevel=0 -verbosity:minimal'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
 
    - job: PrepareAPK
      dependsOn: Build
      steps:
      - powershell: |
          # TODO Make more flexible.
          $apkDirectory = "$env:ANDROIDPROJECT\bin\$env:BUILDCONFIGURATION\net10.0-android"
     
          $apkPattern="*-Signed.apk"
          $apkItems = "$apkDirectory\$apkPattern"
     
          #Debug.
          #Get-ChildItem -Path $apkItems
     
          #Needs created before copy.
          #New-Item -Path "$env:PUBLISHDIRECTORY" -ItemType "directory" -Force
     
          Write-Host "1 $Build.ArtifactStagingDirectory"
          Write-Host "2 $(Build.ArtifactStagingDirectory)"
          Write-Host "3 $env:Build.ArtifactStagingDirectory"
          Write-Host "4 $env:Build_ArtifactStagingDirectory"

          $GitHubDirectory = "$(Build.SourcesDirectory)\$(PUBLISHDIRECTORY)\GitHub"
          Write-Host "5 $GitHubDirectory"
          New-Item -Path $GitHubDirectory -ItemType "directory" -Force
          
          Copy-Item -Path $apkItems -Destination $GitHubDirectory -Force
          #Copy-Item -Path $apkItems -Destination  "$(Build.ArtifactStagingDirectory)" -Force
     
          Copy-Item -Path "docs\MAUI\ReleaseNotes.md" -Destination $GitHubDirectory -Force
          #Copy-Item -Path "docs\MAUI\ReleaseNotes.md" -Destination "$(Build.ArtifactStagingDirectory)" -Force
     
          Set-Location -Path $GitHubDirectory
          #Set-Location -Path "$(Build.ArtifactStagingDirectory)"
     
          #Assumes 1 file. Note Rename-Item cannot overwrite by Force.
          Get-ChildItem -file -filter "$apkPattern" | Rename-Item -newname { $_.name -replace "-Signed", ".$env:RELEASEVERSION"} -Force
        displayName: 'Fix APK name'

    - job: PrepareMSIX
      dependsOn: Build
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'Build MSIX by dotnet'
        inputs:
          command: publish
          arguments:  -f:net10.0-windows10.0.26100.0 -p:PublishProfile=MSIX-win-x64
          publishWebProjects: false
          projects: Portable\RCS.PortableShop
   
      - powershell: |
          # Assume only one package.
     
          Set-Location  -Path "$env:PUBLISHDIRECTORY"
     
          Compress-Archive -Path "*\*.cer", "*\*.msix*" -Force -DestinationPath "RCS.CyclOne.UWP.$env:RELEASEVERSION.zip"
        displayName: 'Zip MSIX package'

  - stage: Deploying
    jobs:
    # TODO Is this needed?
    # TODO Back to building?
    - job: Publish
      steps:
      - task: PublishBuildArtifacts@1
        displayName: 'Publish APK'
        inputs:
          # Note does not accept wildcards for filenames.
          PathtoPublish: '$(publishDirectory)\GitHub\nl.rcsworks.cyclone.maui.$(releaseVersion).apk'
          ArtifactName: ALL
      - task: PublishBuildArtifacts@1
        displayName: 'Publish MSIX'
        inputs:
          # Note does not accept wildcards for filenames.
          PathtoPublish: '$(publishDirectory)\RCS.CyclOne.UWP.$(releaseVersion).zip'
          ArtifactName: MSIX

    - job: WaitForAproval
      dependsOn: Publish
      pool: server # Didn't work self hosted. May take long.
      timeoutInMinutes: 60
      steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: '$(administratorMail)'
          instructions: 'Approval pending for Cyclone $(releaseVersion)'

    - job: Deploy
      dependsOn: WaitForAproval
      steps:
      - task: GitHubRelease@1
        displayName: 'Deploy to GitHub'
        inputs:
          gitHubConnection: 'github.com_a-einstein'
          tagSource: userSpecifiedTag
          tag: '$(releaseVersion)_$(Build.BuildNumber)'
          releaseNotesFilePath: '$(publishDirectory)\GitHub\ReleaseNotes.md'
          #releaseNotesFilePath: '$(System.DefaultWorkingDirectory)/_MAUI/ALL/ReleaseNotes.md'
          changeLogCompareToRelease: lastNonDraftRelease