trigger: 
- master

pool: 
  name: Default

variables:
- group: 'SharedVariables'

stages:
  - stage: Building

    jobs:
    - job: Build

      steps:

      - checkout: self
        clean: false
        submodules: recursive

      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: $(solution)

      - task: VSBuild@1
        displayName: 'Build solution'
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:WarningLevel=0 -verbosity:minimal'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
 
    - job: PrepareAPK
      dependsOn: Build
  
      steps:
  
      - powershell: |
          #TODO Make more flexible.
          $apkDirectory = "$env:ANDROIDPROJECT\bin\$env:BUILDCONFIGURATION\net10.0-android"
     
          $apkPattern="*-Signed.apk"
          $apkItems = "$apkDirectory\$apkPattern"
     
          #Debug.
          #Get-ChildItem -Path $apkItems
     
          #Needs created before copy.
          #New-Item -Path "$env:PUBLISHDIRECTORY" -ItemType "directory" -force
     
          Write-Host "1 $Build.ArtifactStagingDirectory"
          Write-Host "2 $(Build.ArtifactStagingDirectory)"
          Write-Host "3 $env:Build.ArtifactStagingDirectory"
          Write-Host "4 $env:Build_ArtifactStagingDirectory"
     
          Copy-Item -Path $apkItems -Destination "$(PUBLISHDIRECTORY)\GitHub"
          #Copy-Item -Path $apkItems -Destination  "$(Build.ArtifactStagingDirectory)"
     
          Copy-Item -Path "docs\MAUI\ReleaseNotes.md" -Destination  "$(PUBLISHDIRECTORY)\GitHub"
          #Copy-Item -Path "docs\MAUI\ReleaseNotes.md" -Destination  "$(Build.ArtifactStagingDirectory)"
     
          Set-Location  -Path "$(PUBLISHDIRECTORY)\GitHub"
          #Set-Location  -Path "$(Build.ArtifactStagingDirectory)"
     
          #Assumes 1.
          Get-ChildItem -file -filter "$apkPattern" | Rename-Item -newname { $_.name -replace "-Signed", ".$env:RELEASEVERSION"}
        displayName: 'Fix APK name'

    - job: PrepareMSIX
      dependsOn: Build

      steps:
   
      - task: DotNetCoreCLI@2
        displayName: 'Build MSIX by dotnet'
        inputs:
          command: publish
          arguments:  -f:net10.0-windows10.0.26100.0 -p:PublishProfile=MSIX-win-x64
          publishWebProjects: false
          projects: Portable\RCS.PortableShop
   
      - powershell: |
          # Assume only one package.
     
          Set-Location  -Path "$env:PUBLISHDIRECTORY"
     
          Compress-Archive -Path "*\*.cer", "*\*.msix*" -Force -DestinationPath "RCS.CyclOne.UWP.$env:RELEASEVERSION.zip"
        displayName: 'Zip MSIX package'

  - stage: Deploying

    jobs:

    - job: Publish

      steps:
 
      - task: PublishBuildArtifacts@1
        displayName: 'Publish APK'
        inputs:
          PathtoPublish: '$(publishDirectory)\GitHub\RCS.CyclOne.UWP.$(releaseVersion).zip'
          ArtifactName: ALL

      - task: PublishBuildArtifacts@1
        displayName: 'Publish MSIX'
        inputs:
          PathtoPublish: '$(publishDirectory)\RCS.CyclOne.UWP.$(releaseVersion).zip'
          ArtifactName: MSIX

    - job: Deploy

      steps:
      - task: GitHubRelease@1
        displayName: 'Deploy to GitHub'
        inputs:
          gitHubConnection: 'github.com_a-einstein'
          #tagSource: userSpecifiedTag
          #tag: '$(ReleaseTag)'
          releaseNotesFilePath: '$(publishDirectory)\GitHub\ReleaseNotes.md'
          #releaseNotesFilePath: '$(System.DefaultWorkingDirectory)/_MAUI/ALL/ReleaseNotes.md'
          changeLogCompareToRelease: lastNonDraftRelease